name: daily-cron
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API for db keep alive
        run: |
          curl --request GET \
          --url 'https://forum.meucci.party/api/keepalive'
